### ISSUE TITLE
登录二维码

### ISSUE THREAD

**Issue by catalinaLi** [xalexec/jd-scan#1]
老铁现在登录二维码打印在控制台扫不了，我转换了以后显示失效。知道是怎么回事吗？

**Comment by xalexec** [comment]
可能是因为你控制台字体的原因，你可以在 QRCodeUtils scanCode 里输出返回值，自己生成二维码扫描，二维码有时效。另外这个项目之前是用来抢口罩的，现在可能有些功能功能已经失效，需要自已试试看

**Comment by catalinaLi** [comment]
现在就是这个二维码扫描显示失效。感觉像jd登录更新了的样子。

**Comment by xalexec** [comment]
我测试是可以的，下单也正常

**Comment by catalinaLi** [comment]
Emmm。好的，我再看看。麻烦了。抱拳
